### ISSUE TITLE
感谢作者的方法，提些浅薄看法

### ISSUE THREAD

**Issue by heypandax** [snowlyg/gotransformer#1]
作者的反射方式用着很方便，我在使用中做了些优化不知是否合适，提价建议：

#### 1. 在模型中，id类型建议使用uint，因为前端提交的是uint，在基本类型中的int会带来一些不便。

因此我对第125行做了如下修改：
<code>
of.SetInt(int64(inf.FieldByName("ID").Interface().(uint))) // 改为
of.SetUint(uint64(inf.FieldByName("ID").Interface().(uint)))
</code>

#### 2. 在大数据量反射时，交叉匹配类型引起了很多额外的运算，可使用哈希优化。

第 101 行
<code>if into.Name == otf.Name</code>

**Comment by snowlyg** [comment]
非常欢迎提出问题和优化建议，如果可以希望能提交一个优化 pr 过来。

**Comment by heypandax** [comment]
好的，有时间弄。
